import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import MainHeader from "@/components/Header";
import StickyHeader from "@/components/StickyHeader";
import Sections from "./(sections)/Sections";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Enjoy shopping online! Shop furniture &amp; accessories  - IKEAN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${notoSans.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainHeader />
        <StickyHeader />
        <Sections />
        {children}
        <Footer />
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
